require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

target 'App' do
  pod 'Capacitor',                  :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova',           :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorBrowser',           :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorFilesystem',        :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorCommunitySqlite',   :path => '../../node_modules/@capacitor-community/sqlite'

  post_install do |installer|
    assertDeploymentTarget(installer)
  end
end
